contact/urls.py
from django.conf.urls import url
from . import views

app_name = "contact"

urlpatterns = [
        # /
        url(r'^$', views.IndexView.as_view(), name='me'),
        # /form

        url(r'^contact/$', views.contact, name='contact'),
        # /me/update
        url(r'^update/$', views.MeUpdateView.as_view(), name='update')
]

works/urls.py
from django.conf.urls import url
from . import views


app_name = 'works'

urlpatterns = [
    # /
    # /works/
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'^add/', views.WorkCreateView.as_view(), name='add'),
    url(r'^(?P<slug>[-\w]+)/$',
        views.WorkDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-\w]+)/update/$',
        views.WorkUpdateView.as_view(), name='update'),
]

works/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings


class Work(models.Model):
    name = models.CharField(max_length=200)
    short_description = models.CharField(max_length=300, blank=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    link = models.URLField(blank=True)
    image = models.ImageField(upload_to="work-banner", blank=True)
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('work:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Work, self).save(*args, **kwargs)

    @property
    def image_append(self):
        image = self.image
        if settings.DEFAULT_FILE_STORAGE == 'storages.backends.gcloud.GoogleCloudStorage':
            return f"{settings.GS_URL}{image.name}"
        return image.url


class WorkImage(models.Model):
    name = models.ForeignKey(Work, related_name='images',
            on_delete=models.CASCADE)
    image = models.ImageField()
    description = models.TextField()

    def __str__(self):
        return self.name.name + str(self.pk)

    @property
    def image_append(self):
        image = self.image
        if settings.DEFAULT_FILE_STORAGE == 'storages.backends.gcloud.GoogleCloudStorage':
            return f"{settings.GS_URL}{image.name}"
        return image.url


class WorkTechnology(models.Model):
    work = models.ForeignKey(Work, related_name='techs', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

works/forms.py
from django import forms
from .models import Work, WorkTechnology, WorkImage


class WorkForm(forms.ModelForm):
    description = forms.CharField(
            widget=forms.Textarea(
                attrs={'class': 'materialize-textarea'}))

    class Meta:

        model = Work
        fields = [
                'name', 'short_description', 'description',
                 'link', 'image',
                ]

class TechForm(forms.ModelForm):
    class Meta:
        model = WorkTechnology
        fields=('name',)


TechInlineFormSet = forms.inlineformset_factory(
        Work, WorkTechnology,
        extra=1,
        fields=('name',)
        )

class ImageForm(forms.ModelForm):
    description = forms.CharField(
            widget=forms.Textarea(
                attrs={'class': 'materialize-textarea'}))
    class Meta:
        model = WorkImage
        fields=('image', 'description')

ImageInlineFormSet = forms.inlineformset_factory(
        Work, WorkImage,
        extra=2,
        form=ImageForm,
        #fields= ('image', 'description')
        )

works/views.py
#from django.shortcuts import render
from django.views import generic
from .models import Work, WorkTechnology, WorkImage
from contact.forms import ContactForm
from contact.models import Me
from .serializers import WorkSerializer
from rest_framework import viewsets
from rest_framework import permissions
from .forms import WorkForm, TechInlineFormSet, ImageInlineFormSet
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse


class IndexView(generic.ListView):

    def get_queryset(self):
        return Work.objects.filter(hidden=False)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = ContactForm()
        try:
            context['me'] = Me.objects.get(slug='me')
        except:
            context['me'] = ''
        return context


class WorkDetailView(generic.DetailView):
    model = Work


class WorkUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Work
    form_class = WorkForm
    #fields = ('name','short_description', 'description',
    #        'slug','link','image','hidden', 'work.images')

    def get_object(self, queryset=None):
        instance = Work.objects.get(slug=self.kwargs.get('slug',''))
        return instance 

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        techs = WorkTechnology.objects.filter(work=self.object)
        images = WorkImage.objects.filter(name=self.object)
        tech_form = TechInlineFormSet(instance=self.object)
        image_form = ImageInlineFormSet(instance=self.object)
        return self.render_to_response(
                self.get_context_data(form=form, tech_form=tech_form,
                    image_form=image_form)
                )
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        tech_form = TechInlineFormSet(self.request.POST, instance=self.object)
        image_form = ImageInlineFormSet(self.request.POST, instance=self.object)
        if form.is_valid() and tech_form.is_valid() and image_form.is_valid():
            return self.form_valid(form, tech_form, image_form)
        else:
            pass
            #return self.form_invalid(form, tech_form)

    def form_valid(self, form, tech_form, image_form):
        form.save()
        tech_form.save()
        image_form.save()
        return HttpResponseRedirect(self.object.get_absolute_url())



class WorkCreateView(LoginRequiredMixin, generic.CreateView):
    model = Work
    form_class = WorkForm
    template_name = 'works/work_create.html'


class WorkViewSet(viewsets.ModelViewSet):
    queryset = Work.objects.all()
    serializer_class = WorkSerializer
    permission_classes = [permissions.IsAdminUser]

works/templates/works/work_create.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <form action="{% url 'works:add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

  {{ form.as_p }}
<input type="submit" class="btn"/>

  </form>

</div>
{% endblock %}

works/templates/works/work_detail.html
{% extends 'layout.html' %}
{% load markdown %}
{% block extrahead %}

{% endblock %}

{% block body %}

<div class="parallax-container">
  <div class="parallax"><img src="{{ object.image.url }}" class="desaturate"></div>
</div>
<div class="section white">
  <div class="container">
    <div class="row">
      <div class="col l6 m6 s12">
        <div class="details">
          <h2>
              {{ object.name}}
          {% if user.is_authenticated %}
            <a href="{% url 'works:update' object.slug %}">update</a>
          {% endif %}
          </h2>
          <span>Link: <a href="{{ object.link }}">{{ object.link }}</a></span>
          <div class="card-panel grey lighten-4 ">
            {% autoescape  off %}
          <p>{{ object.description | markdown }}</p>
          {% endautoescape %}
          </div>
        </div>
      </div>
      <div class="col l6 m6 s12">
        <div class="technology">
          <h2>Technology</h2>
            <ol>
             {% for tech in object.techs.all %}
              <li>{{ tech.name }}</li>
             {% endfor %}
            </ol>
        </div>
      </div>
    </div>

    <div class="gallery">
        <div class="row">
            <div id="animated-thumb">
                {% for img in object.images.all %}
                <a href="{{ img.image.url }}"><img src="{{ img.image.url }}" alt=""></a>
                {% endfor %}
            
            </div>
        
        </div>
    </div>


  </div>
</div>

{% endblock %}

works/templates/works/work_form.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <form action="{% url 'works:update' object.slug %}" method="post"
        enctype="multipart/form-data">
    {% csrf_token %}

  {{ form.as_p }}
  <h3>Technologies</h3>
  {{ tech_form.management_form }}
  <p>
  
  {% for f in tech_form %}
    <br>
    
    {% for hidden in f.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {{ f.name.label }}{{ f.name }}

    {% if f.name.value %}
        {{ f.DELETE }}
        <label for="id_{{ f.DELETE.html_name }}">
            {{ f.DELETE.name }}
        
        </label>
    {% endif %}
  </p>
  <br>
  


  {% endfor %}

  <h3>Images</h3>
{{ image_form.as_p }}



<button type="submit" class="btn">Submit</button>

  </form>
</div>
{% endblock %}

works/templates/works/work_list.html
{% extends 'layout.html' %}
{% load markdown %}
{% block body %}


<div class="parallax-container">
  <div class="parallax">
    <img src="https://storage.googleapis.com/benray-artwork/MhuMeQo.png" />
  </div>
</div>

<div class="row">
<div class="main-right col s12 m6 l6">

<div class="container">
  <div>
    <div class="me center">

    <img src="{{ me.image.url }}" class="responsive-image">
    <h2>{{ me.user.first_name }} {{ me.user.last_name }}</h2>
    <h6>{{ me.short_description }}</h6>
  </div>

  </div>
  <div class="contact-details center">
      <p><a href="mailto:{{ me.user.email }}">{{ me.user.email }}</a></p>
      <p>{{ me.phone }}</p>
      <p>
      	<a href="https://github.com/merlinsbeard">Github</a>
	|
	<a href="https://gitlab.com/merlinsbeard">Gitlab</a>
      </p>
  </div>
</div>


  <div class="about-me ">
    <div class="container">

      <h5>About me</h5>
      {% autoescape off %}
      <div class="flow-text">
        {{ me.long_description | markdown}}      
      </div >
      {% endautoescape %}

    </div>
  </div>
  <div class="form">
    <div class="container">
      <h2>Get in touch</h2>

    <form action="{% url 'contact:contact' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}


        <div class="input-field">
            {{ form.name.errors }}
            <i class="material-icons prefix">account_circle</i>
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>
        <div class="input-field">
            {{ form.email.errors }}
            <i class="material-icons prefix">email</i>
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="input-field">
            {{ form.message.errors }}
            <i class="material-icons prefix">mode_edit</i>
            {{ form.message }}
            {{ form.message.label_tag }}
        </div>


    <button type="submit" class="btn">Submit</button>

    </form>
    </div>
  </div>
</div>

<div class="main-left col s12 m6 l6">

    <div class="container">
        {% for object in object_list %}
            <div class="row">
              <div class="col s12">
                <div class="card sticky-action grey lighten-4 z-depth-4">
                  <div class="card-image">
                    <img src="{{ object.image.url }}" alt="" class="activator">
                  </div>
                  <div class="card-content black-text">
                    <span class="card-title activator">{{ object.name }}<i class="material-icons right">more_vert</i></span>
                    <p>
                      {{ object.short_description }}
                    </p>
                  </div>
                  <div class="card-reveal">
                    <span class="card-title">{{ object.name}}<i class="material-icons right">close</i></span>
                    <p>
                      {{ object.short_description }}
                    </p>
                    <div class="center links">
                      <a href="{% url 'works:detail' object.slug %}" class="waves-effect btn-large">Learn More!</a>
                    </div>
                  </div>
                  <div class="card-action">
                      {% for tech in object.techs.all %}
                      <div class="chip">{{ tech.name }}</div>
                      {% endfor %}
                      <a href="#modal"></a>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}

    </div>
    <!-- end of main-left -->
</div>






</div>

{% endblock %}