contact/urls.py
from django.conf.urls import url
from . import views

app_name = "contact"

urlpatterns = [
        # /
        url(r'^$', views.IndexView.as_view(), name='me'),
        # /form

        url(r'^contact/$', views.contact, name='contact'),
        # /me/update
        url(r'^update/$', views.MeUpdateView.as_view(), name='update')
]

works/urls.py
from django.conf.urls import url
from . import views


app_name = 'works'

urlpatterns = [
    # /
    # /works/
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'^add/', views.WorkCreateView.as_view(), name='add'),
    url(r'^(?P<slug>[-\w]+)/$',
        views.WorkDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-\w]+)/update/$',
        views.WorkUpdateView.as_view(), name='update'),
]

templates/layout.html

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
     <!-- Global site tag (gtag.js) - Google Analytics -->
     <script async src="https://www.googletagmanager.com/gtag/js?id=UA-91437172-1"></script>
     <script>
	  window.dataLayer = window.dataLayer || [];
	    function gtag(){dataLayer.push(arguments);}
	      gtag('js', new Date());

		gtag('config', 'UA-91437172-1');
     </script>
    <meta charset="utf-8">
    <title>ART</title>

    <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link href="https://fonts.googleapis.com/css?family=Montserrat"
rel="stylesheet">

    <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/lightgallery.js/1.0.1/css/lightgallery.min.css">
     <!-- Compiled and minified JavaScript -->
     <link rel="stylesheet" href="{% static 'works/style.css' %}">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
     {% block extrahead %}
     {% endblock %}

  </head>
  <body>
    <header>
      <div class="container">

        <h1 class="center"><a href="{% url 'home' %}" class="black-text">ART</a></h1>

      </div>
    </header>
    <div class="main_body">
    
      {% block body %}
      {% endblock %}
    </div>
      <div class="fixed-action-btn click-to-toggle">
        <a class="btn btn-large red">
          <i class="large material-icons left">menu</i>Menu
        </a>
        <ul>
          <li>
              {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}" class="btn-floating btn-large">
                Logout

            </a>


              {% else %}
            <a href="{% url 'login' %}" class="btn-floating btn-large">
                Login

            </a>

              {% endif %}
          </li>
          <li>
            <a href="{% url 'home' %}" class="btn-floating btn-large">

              <i class="material-icons left">home</i>
            </a>
          </li>

          <li>
            <a href="{% url 'contact:me' %}" class="btn-floating btn-large">
              <i class="material-icons">email</i>
            </a>
          </li>
        </ul>

      </div>


<div class="parallax-container">
  <div class="parallax">
    <img src="https://storage.googleapis.com/benray-artwork/SBgNYXh.png" alt="">
  </div>
</div>
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/lightgallery.js/1.0.1/js/lightgallery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
     {% block jscript %}
     {% endblock %}

    <script src="{% static 'js/clever_red.js' %}"></script>

  </body>
</html>