contact/urls.py
from django.conf.urls import url
from . import views

app_name = "contact"

urlpatterns = [
        # /
        url(r'^$', views.IndexView.as_view(), name='me'),
        # /form

        url(r'^contact/$', views.contact, name='contact'),
        # /me/update
        url(r'^update/$', views.MeUpdateView.as_view(), name='update')
]

works/urls.py
from django.conf.urls import url
from . import views


app_name = 'works'

urlpatterns = [
    # /
    # /works/
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'^add/', views.WorkCreateView.as_view(), name='add'),
    url(r'^(?P<slug>[-\w]+)/$',
        views.WorkDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-\w]+)/update/$',
        views.WorkUpdateView.as_view(), name='update'),
]

contact/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from markdown import markdown


class Me(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    short_description = models.CharField(max_length=300)
    long_description = models.TextField()
    image = models.ImageField(upload_to="me")
    phone = models.CharField(max_length=40)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.user.first_name + self.user.last_name

    @property
    def name(self):
        full_name = "{} {}".format(
                self.user.first_name, self.user.last_name)
        return full_name

    @property
    def email(self):
        return self.user.email

    @property
    def long_description_html(self):
        return markdown (
            self.long_description
        )


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact, Me
from django.contrib.auth.models import User



class ContactForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'validate'}))
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'materialize-textarea'}))


    class Meta:
        model = Contact
        fields = ('name', 'email', 'message')

    def send_mail(self):
        message = """
                Name: {},
                email: {},
                Message: {}
                date_added: {}
                """.format(
                        self.name, self.email,
                        self.message, self.date_added)
        pass


class MeForm(forms.ModelForm):
    long_description = forms.CharField(
        widget=forms.Textarea(
                attrs={'class': 'materialize-textarea'}))
    first_name = forms.CharField(max_length=256)


    class Meta:
        model = Me
        fields = ['slug', 'short_description', 'long_description', 'phone', 'image']

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

MeFormSet = forms.inlineformset_factory(User, Me, form=MeForm)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email' ]

contact/views.py
from django.shortcuts import render
from django.views import generic
from .models import Me
from .forms import ContactForm, MeForm
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
import os
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import MeSerializer


class IndexView(generic.TemplateView):
    template_name = "contact/me.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        try:
            context['me'] = Me.objects.get(slug='me')
        except:
            context['me'] = ''
        context['form'] = ContactForm
        return context


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            post = form.save(commit=False)
            post.save()
            contact_me_mail(data['name'], data['email'], data['message'])
            context = {'name': data['name'], }
            return render(request, 'contact/success.html', context)
    else:
        form = ContactForm()
    return render(request, 'contact/contactform.html', {'form': form})


# REMOVE THIS when sendmail is done in models.py
def contact_me_mail(from_person, from_email, message):
    # Formated email
    subject = "New Contact from {}".format(from_person)
    message = """
            from: {}
            email: {}
            message: {}
            """.format(from_person, from_email, message)

    to = os.environ['EMAIL_TO']
    to = settings.EMAIL_TO
    from_ = settings.EMAIL_HOST_USER
    send_mail(subject, message, from_, [to], fail_silently=False)


class MeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Me
    form_class = MeForm
    template_name = 'contact/me_update.html'

    def get_success_url(self):
        return reverse('contact:me')

    def get_object(self, queryset=None):
        return self.request.user.me


class MeApiView(APIView):
    def get(self, request, format=None):
        me = Me.objects.get(slug="me")
        serializer = MeSerializer(me)
        return Response(serializer.data)

contact/templates/contact/contactform.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">



    <form action="{% url 'contact:contact' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}


        <div class="input-field">
            {{ form.name.errors }}
            <i class="material-icons prefix">account_circle</i>
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>
        <div class="input-field">
            {{ form.email.errors }}
            <i class="material-icons prefix">email</i>
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="input-field">
            {{ form.message.errors }}
            <i class="material-icons prefix">mode_edit</i>
            {{ form.message }}
            {{ form.message.label_tag }}
        </div>


    <button type="submit" class="btn">Submit</button>

    </form>
</div>

{% endblock %}

contact/templates/contact/me.html
{% extends 'layout.html' %}
{% load markdown %}
{% block body %}

<div class="container">
  <header >
    <div class="me center">
        <img src="{{ me.image.url }}" class="responsive-image">
    <h4>
        {{ me.user.first_name }} {{ me.user.last_name }}

        {% if user.is_authenticated %}
        <a href="{% url 'contact:update' %}">Update</a>
        {% endif %}
    </h4>

    <h6>{{ me.short_description }}</h6>
  </div>

  </header>
  <div class="contact-details center">
      <p>{{ me.user.email }}</p>

      <p>{{ me.phone }}</p>
      <p>
      	<a href="https://github.com/merlinsbeard">Github</a>
	|
	<a href="https://gitlab.com/merlinsbeard">Gitlab</a>
      </p>
  </div>
</div>


  <div class="card-panel about-me teal lighten-4 ">
    <div class="container">

      <h5>About me</h5>
      {% autoescape off %}
      <p class="flow-text">
        {{ me.long_description | markdown }}      
      </p>
      {% endautoescape %}

    </div>
  </div>
  <div class="form">
    <div class="container">
      <h2>Get in touch</h2>

    <form action="{% url 'contact:contact' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}


        <div class="input-field">
            {{ form.name.errors }}
            <i class="material-icons prefix">account_circle</i>
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>
        <div class="input-field">
            {{ form.email.errors }}
            <i class="material-icons prefix">email</i>
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="input-field">
            {{ form.message.errors }}
            <i class="material-icons prefix">mode_edit</i>
            {{ form.message }}
            {{ form.message.label_tag }}
        </div>


    <button type="submit" class="btn">Submit</button>

    </form>
    </div>
  </div>

{% endblock %}

contact/templates/contact/me_update.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <div class="me center">
    
    <img src="{{ form.instance.image.url }}" class="responsive-image">
    </div>    
  <div class="contact-details center">
      <p>
    {{ form.instance.full_name | title }}
      </p>
      <p>{{ form.instance.user.email }}</p>

  </div>
    <form action="{% url 'contact:update' %}" method="post"
        enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}
<button type="submit" class="btn">Submit</button>

  </form>
</div>

{% endblock %}

contact/templates/contact/success.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <h4>Hello {{ name | title }}! I've successfully received your message!</h4>

</div>

{% endblock %}